FROM node:22-alpine
# source image info: https://hub.docker.com/_/node/

ARG PROJECT_ID

USER node
COPY --chown=node:node . /usr/app
WORKDIR /usr/app

ENV DOCKER=true

RUN npm ci

ENV NODE_ENV=production
ENV GCLOUD_RUN=$PROJECT_ID

RUN npm run build:shell

ENTRYPOINT ["node", "apps/shell"]