FROM node:21-alpine
# source image info: https://hub.docker.com/_/node/

ENV NODE_ENV=production
ENV DOCKER=true

USER node
COPY --chown=node:node . /usr/app
WORKDIR /usr/app

RUN npm i
RUN npm run build:shell

ENTRYPOINT ["node", "apps/shell"]