FROM node:22-alpine
# source image info: https://hub.docker.com/_/node/

ARG PROJECT_ID

USER node
COPY --chown=node:node . /usr/app
WORKDIR /usr/app

ENV NODE_ENV=production
ENV DOCKER=true
ENV GCLOUD_RUN=$PROJECT_ID

RUN npm ci

RUN npm run build:content

ENTRYPOINT ["node", "apps/content"]