FROM node:23-alpine
# source image info: https://hub.docker.com/_/node/

USER node
COPY --chown=node:node . /usr/app
WORKDIR /usr/app

RUN npm ci

ENV NODE_ENV=production
ENV DOCKER=true

RUN npm run build:content

ENTRYPOINT ["node", "apps/content"]